### PR TITLE
Add Cargo.lock

### PR DESCRIPTION
**Pull request by DieracDelta**
Hello! I'd like to package this with nix. In order to do so, I'd need a `Cargo.lock` file to be committed. Would yall be willing to pull in a Cargo.lock? It also seems like this is [suggested for rust binaries](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries).

### CODE REVIEW

**Comment by taiki-e** [comment]
Thanks for the PR!

It is somewhat intentional that we are not currently committing lockfile.

- [cargo *automatically* publishes Cargo.lock when there is binary in a crate](https://github.com/rust-lang/cargo/issues/7169#issuecomment-539168339).
  The cargo documentation you mention does not mention this so it seems a bit outdated.

- `cargo install` ignores `Cargo.lock` by default and uses the latest dependencies.
  If we commit `Cargo.lock` and don't update it on a regular basis, our CI cannot guarantee that crate is working properly with the latest dependencies at the time of release. (Given that many people are installing binary crates without using --locked, that can actually be a problem.)

- Tools for automatically updating Rust's dependencies are not good. Dependabot for Rust projects that include lockfile is not configurable enough and is noisy.

That said, I'm open to accepting this if non-cargo package managers require it.

**Comment by taiki-e** [comment]
> if non-cargo package managers require it.

Hmm, I thought the package manager could use `cargo install --locked --target-dir ...`, but that probably won't work if they want to apply their own patches.

**Comment by DieracDelta** [comment]
Ah, I didn't realize that `crates.io` hosted a version of the repo as a tarball that contains a Cargo.lock. I can just point nix at that, so I'll close this. Thanks for the quick and detailed response!

**Comment by WhyNotHugo** [comment]
> That said, I'm open to accepting this if non-cargo package managers require it.

Typically, distributions want deterministic results. A lockfile ensures that the same dependencies are used on each rebuild, but without a lockfile, rebuilding the same package version can yield diverging results.

**Pull request closed without merging**
