### PR TITLE
document --profile --cargo-profile --config-path

### PR DESCRIPTION
**Pull request by TriplEight**
cc https://github.com/taiki-e/cargo-llvm-cov/issues/267
cc https://github.com/taiki-e/cargo-llvm-cov/pull/269

### CODE REVIEW

**Comment by taiki-e** [comment]
We have intentionally not documented nextest-specific options; as the help message states, you can refer to them using `cargo nextest run --help`.

https://github.com/taiki-e/cargo-llvm-cov/blob/08015c42a5537e714a03b2c1f1cbbd323ea0643e/docs/cargo-llvm-cov-nextest.txt#L10

The reasons are the same as those stated in https://github.com/taiki-e/cargo-llvm-cov/issues/267#issuecomment-1528786158.

> This design eliminates the need to respond to each addition or deletion of CLI flags and also makes it easier to maintain compatibility with older cargo-nextest.



Also what you are editing is a help message for subcommands unrelated to nextest.

**Comment by TriplEight** [comment]
> We have intentionally not documented nextest-specific options; as the help message states, you can refer to them using cargo nextest run --help.

Thanks for the clarification, I understand. But there's a certain confusion in `cargo` native and `nextest` `--profile` and `--cargo-profile` flags. I wanted to address it.

**Comment by TriplEight** [comment]
Maybe it makes sense to have a "supported nextest flags" category,
as per https://github.com/taiki-e/cargo-llvm-cov/issues/267#issuecomment-1528786158
> cargo-llvm-cov doesn't parse all the cargo-nextest CLI flags, but only those necessary for cargo-llvm-cov to work properly, and just passthrough everything else to the cargo-nextest.

**Comment by taiki-e** [comment]
> as per [#267 (comment)](https://github.com/taiki-e/cargo-llvm-cov/issues/267#issuecomment-1528786158)
> 
> > cargo-llvm-cov doesn't parse all the cargo-nextest CLI flags, but only those necessary for cargo-llvm-cov to work properly, and just passthrough everything else to the cargo-nextest.

What I mentioned there relates to flags that do not work unless the cargo-llvm-cov also recognizes them, and there are in fact many flags that work just fine even if the cargo-llvm-cov does not recognize them.

It would be great if someone could exhaustively test for compatibility with cargo-nextest options, document and issue warnings about options that don't work, but that would require a lot of work.

**Comment by taiki-e** [comment]
Closing in favor of https://github.com/taiki-e/cargo-llvm-cov/issues/271. Thanks anyway for the PR.

**Pull request closed without merging**
