### PR TITLE
Exclude build script by default

### LINKED ISSUE #159: Exclude build.rs from coverage reports
Parts of a project that are loaded from `build.rs` have duplicated coverage reports, both under the standard package name and under the `build_script_build::` module prefix.

### PR DESCRIPTION
**Pull request by taiki-e**
Closes #159

### CODE REVIEW

**Comment by stouset** [comment]
Does this actually remove the `build_script_build` module from coverage results? By my (potentially-inaccurate) reading it looks like it just adds a flag that lets you opt in or out, but the logic for actually excluding those results hasn't changed. So it looks like if you opt out you just end up with the same behavior as what happened previously, no?

**Comment by taiki-e** [comment]
> the logic for actually excluding those results hasn't changed

No. Changes to src/main.rs will change to ignore artifacts related to build scripts if --include-build-script flag is not passed.

```rs
if cx.cov.include_build_script {
    let dir = p.file_name().unwrap().to_string_lossy();
    if !cx.build_script_re.is_match(&dir) {
        return false;
    }
} else {
    // `false` means "ignore this path"
    return false;
}
```

If all corresponding artifacts are ignored, the file (and the module) will not be displayed in the report.

cov163

cov163-2

**Comment by taiki-e** [comment]
Published in 0.4.0.

**Comment by stouset** [comment]
I must have misunderstood the contents of the patch then. Thank you for the quick turnaround!

**Comment by stouset** [comment]
Confirmed that this works as expected now. Thanks again!

**Pull request merged**
