### PR TITLE
Fix generic code hit by doctests not correctly remapped

### PR DESCRIPTION
**Pull request by Swatinem**
`cargo-llvm-cov` currently uses `--remap-path-prefix` internally (not sure for the reason why?).
However that option is not recognized by rustdoc at the moment, which means that generic code that is instantiated in doctests is not counted towards the coverage, as it ends up in a "different" file as far as llvm tools are concerned.

I think in order to fix this, the flag needs to be supported in rustdoc as well, and I am exploring that option right now, so stay tuned.

relates to #2

I opened https://github.com/rust-lang/rust/pull/92648 for the necessary changes in rustdoc, with which I generated the test snapshots in this PR, however I would like to somehow increase the confidence here a bit. Also I have seen that there is some code that does feature detection, and it might be a good idea to do that for this flag as well (and gate the test on the flag being available). Can you maybe point me in the right direction how to best do that?

### CODE REVIEW

**Comment by taiki-e** [comment]
> `cargo-llvm-cov` currently uses `--remap-path-prefix` internally (not sure for the reason why?).

IIRC, this was needed because sometimes macros are displayed with absolute path in HTML reports. 

https://github.com/taiki-e/cargo-llvm-cov/blob/30efe472911693470cca4a8491ac3abea73ac423/src/main.rs#L205-L206

I guess the underlying bug has not been fixed yet, but currently the [ignore_filename_regex](https://github.com/taiki-e/cargo-llvm-cov/blob/30efe472911693470cca4a8491ac3abea73ac423/src/main.rs#L583) excludes a few more directories, so I don't think those will displayed in the report anyway.

**Comment by Swatinem** [comment]
Are you suggesting the flag might not be necessary after all?

**Comment by taiki-e** [comment]
> Are you suggesting the flag might not be necessary after all?

Yes

**Comment by Swatinem** [comment]
uff… I tried to do that, but now all the snapshot tests have randomized paths in them. I give up 😓

**Comment by taiki-e** [comment]
(I'm starting to think to provide an option to disable --remap-path-prefix: https://github.com/taiki-e/cargo-llvm-cov/issues/140#issuecomment-1055457353)

**Comment by taiki-e** [comment]
Closing as https://github.com/rust-lang/rust/pull/92648 has been closed.

Also, --remap-path-prefix is optional since cargo-llvm-cov 0.3 (https://github.com/taiki-e/cargo-llvm-cov/pull/141), so the problem may no longer be reproducible without the --remap-path-prefix option.

Thanks anyway for the PR!

**Pull request closed without merging**
