### PR TITLE
Use -Clink-dead-code

### LINKED ISSUE #21: 100% coverage is incorrectly reported
I don't know the details yet, but I have seen 100% coverage is incorrectly reported in some crates.

### PR DESCRIPTION
**Pull request by taiki-e**
Fixes #21

The unstable book says that unused functions are also instrumented, but it seems that -Clink-dead-code is also needed.

https://doc.rust-lang.org/nightly/unstable-book/compiler-flags/instrument-coverage.html#-z-instrument-coverageoptions

> -Z instrument-coverage=all: Instrument all functions, including unused functions and unused generics. (This is the same as -Z instrument-coverage, with no value.)

### CODE REVIEW

**Comment by taiki-e** [comment]
> The unstable book says that unused functions are also instrumented, but it seems that -Clink-dead-code is also needed.
> 
> https://doc.rust-lang.org/nightly/unstable-book/compiler-flags/instrument-coverage.html#-z-instrument-coverageoptions
> 
> > -Z instrument-coverage=all: Instrument all functions, including unused functions and unused generics. (This is the same as -Z instrument-coverage, with no value.)

FYI @richkadel If this is not the intended behavior.

**Comment by richkadel** [comment]
I don't think `-Clink-dead-code` should have any impact.

In fact, that option is known to break the coverage workflow in some cases (particularly on MSVC/Windows builds).

Why, what makes you think it is operating differently without that option?

**Comment by richkadel** [comment]
Ah, I just reviewed your updated test. Correct me if I'm wrong. It looks like you are adding `-Clink-dead-code` in order to get coverage for an entire mod. Apparently, without it, coverage ignores the file or ignores the mod (I'm not sure which).

That should be filed as an issue against `rust-lang/rust` and maybe I can figure out how to get coverage to include unused mods / files without requiring the troublesome `-Clink-dead-code`.

I would advise against adding `-Clink-dead-code` for coverage, or make it opt-in with a warning to "use at your own risk".

Thoughts?

**Comment by taiki-e** [comment]
Thanks for your advice! I opened https://github.com/rust-lang/rust/issues/86177 to report this problem.

And for `-Clink-dead-code`, I'll revert this PR and mention the known workarounds and how they are likely to cause another problem.

**Pull request merged**
