### PR TITLE
Use extract-to if using --archive-file with nextest

### PR DESCRIPTION
**Pull request by magnusja**
Addresses https://github.com/taiki-e/cargo-llvm-cov/issues/265

Fails with
```
error: no input files specified. See llvm-profdata merge -help
error: failed to merge profile data: process didn't exit successfully: `/home/magnus/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-profdata merge -sparse -f /home/magnus/Documents/code/luminovo/epibator/rust-workspace/target/llvm-cov-target/rust-workspace-profraw-list -o /home/magnus/Documents/code/luminovo/epibator/rust-workspace/target/llvm-cov-target/rust-workspace.profdata` (exit status: 1)
```

That file rust-workspace-profraw-list is 0 bytes.

Not sure what is going on, maybe you can hint me what to check.

Closes: #265

### CODE REVIEW

**Comment by magnusja** [comment]
Oh so these profraw files are created during compilation?

Then I guess I need to wrap around this command as well
```
cargo nextest archive --archive-file nextest-archive.tar.zst
```

Currently I think you are defaulting to `nextest run` always.

**Comment by magnusja** [comment]
Update:

So unfortunately, the archive nextest creates do not include the profraw files or the `llvm-cov-target` folder. If I create the archive manually from `target/` nextest complains that the directory structure is not as expected

**Comment by taiki-e** [comment]
If you need a different target directory than the default, you can adjust it here:

https://github.com/taiki-e/cargo-llvm-cov/blob/5f904dad0d58400a58d3df5d5df238a454fa4b12/src/cargo.rs#L65-L76

I don't understand why we need a new subcommand, though.

**Comment by taiki-e** [comment]
Ok, the following patch should fix the problem.

```diff
diff --git a/src/main.rs b/src/main.rs
index c45191b..de0284d 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -648,6 +648,11 @@ fn walk_target_dir<'a>(
     // This is not the ideal way, but the way unstable book says it is cannot support them.
     // https://doc.rust-lang.org/nightly/rustc/instrument-coverage.html#tips-for-listing-the-binaries-automatically
     let mut target_dir = cx.ws.target_dir.clone();
+    if cx.args.subcommand == Subcommand::Nextest
+        && cx.args.cargo_args.iter().any(|a| a == "--archive-file")
+    {
+        target_dir.push("target");
+    }
     // https://doc.rust-lang.org/nightly/cargo/guide/build-cache.html
     if let Some(target) = &cx.args.target {
         target_dir.push(target);
```

**Comment by taiki-e** [comment]
What is the status of this? As far as I know, if you apply my patch, this should be mergeable, but is there any other problem?

**Comment by magnusja** [comment]
Let me try that patch. 

I think the problem was that nextest still was not really happy with the structure, but I forgot I have to check again, sorry

**Pull request merged**
