### PR TITLE
Make object paths relative where possible.

### LINKED ISSUE #124: Generating coverage report fails on Windows with too many objects
See this failed CI output from a coverage run: https://github.com/PyO3/pyo3/runs/4793968532?check_suite_focus=true

It seems this is a symptom of collecting coverage on a large number of output objects, and gives the error `(never executed): The filename or extension is too long. (os error 206)`. I don't actually think it's the filename or extension, but rather the total length of the command. In this case I believe it's something like 34,565 characters long (!) and the limit in Windows is apparently [32,768](https://stackoverflow.com/a/28452546/333308).

I am happy to work on a fix/workaround if somebody knows one, but I also unfortunately don't have direct access to a Windows machine at the moment.

### PR DESCRIPTION
**Pull request by aganders3**
Fixes #124 (well, alleviates it in some circumstance).

Thanks for the suggestion. This seems to just work so I think the part of the docs I was confused about is not related to relative paths of the CLI inputs.

### CODE REVIEW

**Review by taiki-e — COMMENTED** [review]
LGTM. Could you solve [clippy warning](https://github.com/taiki-e/cargo-llvm-cov/runs/4830632616?check_suite_focus=true)?

**Comment by aganders3** [comment]
Oops, fixed. Thanks for the quick review!

**Review by taiki-e — APPROVED** [review]
Thanks!

bors r+

**Comment by taiki-e** [comment]
Published in 0.1.16.

**Pull request merged**
