### PR TITLE
Re-enable multiple values for `package` arg

### PR DESCRIPTION
**Pull request by aganders3**
I think this may have been dropped in the Clap update. I only noticed because the pyo3 CI uses it and is pinned to 0.1.11.

See here for the error: https://github.com/PyO3/pyo3/runs/4829748531?check_suite_focus=true

Hopefully this is another quick merge, but I'm also happy to close and fix there if this was intentionally removed.

### CODE REVIEW

**Comment by aganders3** [comment]
It might also be good to check the tests match for both arg configs. I can work on that later if you think it would add value.

**Comment by aganders3** [comment]
I guess this has a chance of breaking where people are using `--package` or `--exclude` along with a positional arg. I do think the feature is useful but we could also add/enforce comma as a delimiter.

**Comment by taiki-e** [comment]
Thanks for the PR. To be honest, I'm a bit confused about clap's behavior here.

As of cargo-llvm-cov 0.1.0, I thought I had explicitly dropped this behavior: https://github.com/taiki-e/cargo-llvm-cov/commit/e1199da170a312c57cbdaab0a6c8f6b4e4e77dc5
This is to make it consistent with the cargo behavior:

```console
$ cargo build --package "crossbeam-channel crossbeam-deque"
error: invalid character ` ` in pkgid: `crossbeam-channel crossbeam-deque`, characters must be Unicode XID characters (numbers, `-`, `_`, or most letters)

$ cargo build --package crossbeam-channel crossbeam-deque
error: Found argument 'crossbeam-deque' which wasn't expected, or isn't valid in this context
```

And the clap documentation at the time said the following:

https://docs.rs/clap/3.0.0-beta.4/clap/struct.Arg.html#method.multiple_occurrences

> For example, --opt val1 --opt val2 is allowed, but --opt val1 val2 is not.

However, from the changes in the help message, it seems that it was actually implemented in clap 3.0.0-rc.3: https://github.com/taiki-e/cargo-llvm-cov/commit/ab9832fb86d12e9c9a4811099e2971ba7d475d5f

As a result, this became a regression that was introduced in cargo-llvm-cov 0.1.13.

**Review by taiki-e — APPROVED** [review]
So I think it makes sense to support this in cargo-llvm-cov 0.1.x for compatibility, but would like to remove it in cargo-llvm-cov 0.2.0.

bors r+

**Comment by taiki-e** [comment]
> I guess this has a chance of breaking where people are using `--package` or `--exclude` along with a positional arg.

We don't have any positional arguments, so I think this is fine.

**Comment by aganders3** [comment]
Thanks! I agree the clap docs are/were confusing on this feature. It seems there were a number of changes to it through the beta.

**Pull request merged**
